### ISSUE TITLE
Dispatch Array of Jobs

### ISSUE THREAD

**Issue by milsanore** [fhteam/laravel-amqp#15]
Hi, firstly thank you for the awesome library, I have been using it for ~6 months and it's working great.
This is probably more of a Laravel question, but I'm curious if you've solved it internally. 
I need to push hundreds of jobs onto a queue, and my rabbitMQ server lives on a different machine, so the network latency really adds up (e.g. 0.01s latency * 300 jobs => 3 seconds). Is it possible to push an array of jobs onto a queue?
Thanks again,

**Comment by FractalizeR** [comment]
Hi.

Yeah, there is a way to batch messages you send with AMQP. It's simple. If you look [here](https://github.com/fhteam/laravel-amqp/blob/master/src/Queue/AMQPQueue.php#L147), you will see, that we call basic_publish to publish a message inside `push()` method of the `Queue` class.

What we need, is something like `Queue::addMessageToBatch()` and `Queue::pushBatch()` in addition to our `Queue::push()`. The former should act exactly like `Queue::push()`, but calling `AMPQChannel::batch_basic_publish` instead of basic_publish() and the latter just need to call `AMQPChannel::publish_batch()`.

There are also some settings like `AMQPChannel::publish_cache_max_size` which is desired to put to settings.

I would appreciate any PR with tests, if possible, for this since this is a really important feature for systems with high throughput. If you will have problems with it, just ping me here.

**Comment by milsanore** [comment]
Thanks @FractalizeR , your help is always appreciated. I won't have the time to implement this with the care that it deserves for the next few months, I'll let you know when I get started.

**Comment by FractalizeR** [comment]
OK, I will try to have a look on some weekend. Until then let's keep this opened.

**Comment by FractalizeR** [comment]
I've pushed promised changes to master. You can test them. I haven't tagged them yet.

**Comment by FractalizeR** [comment]
Is there any news here? :)

**Comment by milsanore** [comment]
I'm afraid not. I will close, and if we see any issues I'll re-open.
Thanks,

**Comment by FractalizeR** [comment]
Ok, welcome!
